//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UChallenge.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UChallenge.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de Ponderação.
        /// </summary>
        public static string FeiraLivre_AreaDePonderacao {
            get {
                return ResourceManager.GetString("FeiraLivre_AreaDePonderacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string FeiraLivre_Bairro {
            get {
                return ResourceManager.GetString("FeiraLivre_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Distrito.
        /// </summary>
        public static string FeiraLivre_CodigoDistrito {
            get {
                return ResourceManager.GetString("FeiraLivre_CodigoDistrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Subprefeitura.
        /// </summary>
        public static string FeiraLivre_CodigoSubPrefeitura {
            get {
                return ResourceManager.GetString("FeiraLivre_CodigoSubPrefeitura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string FeiraLivre_Logradouro {
            get {
                return ResourceManager.GetString("FeiraLivre_Logradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Distrito.
        /// </summary>
        public static string FeiraLivre_NomeDistrito {
            get {
                return ResourceManager.GetString("FeiraLivre_NomeDistrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Feira.
        /// </summary>
        public static string FeiraLivre_NomeFeira {
            get {
                return ResourceManager.GetString("FeiraLivre_NomeFeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Subprefeitura.
        /// </summary>
        public static string FeiraLivre_NomeSubPrefeitura {
            get {
                return ResourceManager.GetString("FeiraLivre_NomeSubPrefeitura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string FeiraLivre_Numero {
            get {
                return ResourceManager.GetString("FeiraLivre_Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referência.
        /// </summary>
        public static string FeiraLivre_Referencia {
            get {
                return ResourceManager.GetString("FeiraLivre_Referencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região por Divisão em 5 Áreas.
        /// </summary>
        public static string FeiraLivre_RegiaoPorDivisaoEm5Areas {
            get {
                return ResourceManager.GetString("FeiraLivre_RegiaoPorDivisaoEm5Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região por Divisão em 8 Áreas.
        /// </summary>
        public static string FeiraLivre_RegiaoPorDivisaoEm8Areas {
            get {
                return ResourceManager.GetString("FeiraLivre_RegiaoPorDivisaoEm8Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro da Feira.
        /// </summary>
        public static string FeiraLivre_RegistroFeira {
            get {
                return ResourceManager.GetString("FeiraLivre_RegistroFeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor Censitário.
        /// </summary>
        public static string FeiraLivre_SetorCensitario {
            get {
                return ResourceManager.GetString("FeiraLivre_SetorCensitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; length is invalid. Should be between {0} and {1} characters..
        /// </summary>
        public static string Field_InvalidLength {
            get {
                return ResourceManager.GetString("Field_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be a number greater than zero..
        /// </summary>
        public static string Field_InvalidNumber_MustBeGreatherThenZero {
            get {
                return ResourceManager.GetString("Field_InvalidNumber_MustBeGreatherThenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is Required. Please, inform a value..
        /// </summary>
        public static string Field_IsRequired {
            get {
                return ResourceManager.GetString("Field_IsRequired", resourceCulture);
            }
        }
    }
}
